language: node_js

node_js:
  - "8"

# 缓存依赖
cache:
  directories:
    - $HOME/.npm

before_install:
  - export TZ='Asia/Shanghai' # 更改时区

# 依赖安装
install:
  - npm install
  # 安装 NexT 主题
  # - git clone https://github.com/theme-next/hexo-theme-next themes/next
  # 安装主题需要的插件
  # - git clone https://github.com/theme-next/theme-next-fancybox3 themes/next/source/lib/fancybox

# 构建脚本
script:
    # 生成静态站点文件
  - hexo generate

# 分支白名单
branches:
  only:
    - hexo # 只对 hexo 分支进行构建

# GitHub Pages 部署
deploy:
  provider: pages
  skip_cleanup: true
  # 在项目仪表盘的 Settings -> Environment Variables 中配置
  github_token: $GITHUB_TOKEN
  # 将 public 目录下的内容推送到 master 分支上（必须）
  local_dir: public
  target-branch: master
  # fqdn: $CUSTOM_DOMAIN
  # name: $GIT_NAME
  # email: $GIT_EMAIL
  on:
    branch: hexo