language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

install:
  - gem install bundler
  - bundle install

script:
  - bundle exec jekyll build

# deploy to gh_pages branch 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  # local_dir: _site
  on:
    branch: jekyll

